package source;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import source.Home;
import java.awt.Color;
import java.util.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */


public class Registerfrm extends javax.swing.JFrame {

    /**
     * Creates new form Registerfrm
     */
    
    String Gender; 
    String Age;
    String Sports;
    String Dates;
    public Registerfrm() {
        initComponents();
        groupradioGender();
       // groupcheckSports();
       // groupcheckDays();
        }
     public void groupradioGender(){
        buttonGroup1.add(rbtnmale);
        buttonGroup1.add(rbtnfemale);
        }
     

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblwelcome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        txtadrs = new javax.swing.JTextField();
        lbladrs = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbltele = new javax.swing.JLabel();
        txttele = new javax.swing.JTextField();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        lblgender = new javax.swing.JLabel();
        lbldays = new javax.swing.JLabel();
        cbathletic = new javax.swing.JCheckBox();
        cbbton = new javax.swing.JCheckBox();
        cbswim = new javax.swing.JCheckBox();
        cbvball = new javax.swing.JCheckBox();
        cbnball = new javax.swing.JCheckBox();
        cbcarom = new javax.swing.JCheckBox();
        cbchess = new javax.swing.JCheckBox();
        cbttennis = new javax.swing.JCheckBox();
        lblsports = new javax.swing.JLabel();
        cbmon = new javax.swing.JCheckBox();
        cbfri = new javax.swing.JCheckBox();
        cbtue = new javax.swing.JCheckBox();
        cbwed = new javax.swing.JCheckBox();
        cbsat = new javax.swing.JCheckBox();
        cbsun = new javax.swing.JCheckBox();
        cbthu = new javax.swing.JCheckBox();
        lbluname = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        lblpswd = new javax.swing.JLabel();
        lblpswdagain = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        lblnic = new javax.swing.JLabel();
        ptxtpswd = new javax.swing.JPasswordField();
        ptxtpswdconfirm = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtday = new javax.swing.JTextField();
        txtxSports = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(2500, 700));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register.jpg"))); // NOI18N
        jLabel1.setText("WELCOMR TO CC SPORTS CLUB");

        lblwelcome.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(204, 204, 255));
        lblwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblwelcome.setText("WELLCOME TO CC SPORTS CLUB");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        lblfname.setForeground(new java.awt.Color(255, 255, 255));
        lblfname.setText("Full Name");

        lbladrs.setForeground(new java.awt.Color(255, 255, 255));
        lbladrs.setText("Address ");

        lblage.setForeground(new java.awt.Color(255, 255, 255));
        lblage.setText("Age");

        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("Email");

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });

        lbltele.setForeground(new java.awt.Color(255, 255, 255));
        lbltele.setText("Telephone");

        txttele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtteleKeyPressed(evt);
            }
        });

        rbtnmale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnmale.setText("Male");
        rbtnmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmaleActionPerformed(evt);
            }
        });

        rbtnfemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnfemale.setText("Female");
        rbtnfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfemaleActionPerformed(evt);
            }
        });

        lblgender.setForeground(new java.awt.Color(255, 255, 255));
        lblgender.setText("Gender");

        lbldays.setForeground(new java.awt.Color(255, 255, 255));
        lbldays.setText("Days :");

        cbathletic.setForeground(new java.awt.Color(255, 255, 255));
        cbathletic.setText("Athletics");
        cbathletic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbathleticActionPerformed(evt);
            }
        });

        cbbton.setForeground(new java.awt.Color(255, 255, 255));
        cbbton.setText("Batminton");
        cbbton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbtonActionPerformed(evt);
            }
        });

        cbswim.setForeground(new java.awt.Color(255, 255, 255));
        cbswim.setText("Swimming");
        cbswim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbswimActionPerformed(evt);
            }
        });

        cbvball.setForeground(new java.awt.Color(255, 255, 255));
        cbvball.setText("Volleyball");
        cbvball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbvballActionPerformed(evt);
            }
        });

        cbnball.setForeground(new java.awt.Color(255, 255, 255));
        cbnball.setText("Netball");
        cbnball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnballActionPerformed(evt);
            }
        });

        cbcarom.setForeground(new java.awt.Color(255, 255, 255));
        cbcarom.setText("Carom");
        cbcarom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcaromActionPerformed(evt);
            }
        });

        cbchess.setForeground(new java.awt.Color(255, 255, 255));
        cbchess.setText("Chess");
        cbchess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbchessActionPerformed(evt);
            }
        });

        cbttennis.setForeground(new java.awt.Color(255, 255, 255));
        cbttennis.setText("Table Tennis");
        cbttennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbttennisActionPerformed(evt);
            }
        });

        lblsports.setForeground(new java.awt.Color(255, 255, 255));
        lblsports.setText("Sports :");

        cbmon.setForeground(new java.awt.Color(255, 255, 255));
        cbmon.setText("Monday");
        cbmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonActionPerformed(evt);
            }
        });

        cbfri.setForeground(new java.awt.Color(255, 255, 255));
        cbfri.setText("Friday");
        cbfri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfriActionPerformed(evt);
            }
        });

        cbtue.setForeground(new java.awt.Color(255, 255, 255));
        cbtue.setText("Tuesday");
        cbtue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtueActionPerformed(evt);
            }
        });

        cbwed.setForeground(new java.awt.Color(255, 255, 255));
        cbwed.setText("Wednesday");
        cbwed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbwedActionPerformed(evt);
            }
        });

        cbsat.setForeground(new java.awt.Color(255, 255, 255));
        cbsat.setText("Saturday");
        cbsat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsatActionPerformed(evt);
            }
        });

        cbsun.setForeground(new java.awt.Color(255, 255, 255));
        cbsun.setText("Sunday");
        cbsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsunActionPerformed(evt);
            }
        });

        cbthu.setForeground(new java.awt.Color(255, 255, 255));
        cbthu.setText("Thursday");
        cbthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbthuActionPerformed(evt);
            }
        });

        lbluname.setForeground(new java.awt.Color(255, 255, 255));
        lbluname.setText("Give A User Name");

        txtuname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtunameKeyPressed(evt);
            }
        });

        lblpswd.setForeground(new java.awt.Color(255, 255, 255));
        lblpswd.setText("Give A Password");

        lblpswdagain.setForeground(new java.awt.Color(255, 255, 255));
        lblpswdagain.setText("Confirm Password");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnregister.setBackground(new java.awt.Color(102, 102, 102));
        btnregister.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC");

        ptxtpswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptxtpswdKeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age between 10 - 20 years old", "Age between 20 - 30 years old", "Age between 30 - 40 years old", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        txtday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdayMouseClicked(evt);
            }
        });
        txtday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdayKeyPressed(evt);
            }
        });

        txtxSports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtxSportsMouseClicked(evt);
            }
        });
        txtxSports.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtxSportsKeyPressed(evt);
            }
        });

        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfnameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbltele, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttele, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(rbtnmale)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnfemale))
                                .addComponent(lblnic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbladrs, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtadrs, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txtfname, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblpswdagain, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(lbluname)
                                            .addComponent(lblpswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtuname, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                            .addComponent(ptxtpswd)
                                            .addComponent(ptxtpswdconfirm)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnregister)
                                        .addGap(47, 47, 47)
                                        .addComponent(jButton1)))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtxSports, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblsports, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(cbvball, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(cbswim, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbnball, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbcarom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbchess, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbttennis))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbathletic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbbton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)))
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbwed, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbsun, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbthu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbldays, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbtue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbmon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbsat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbfri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblwelcome)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbldays)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbmon)
                                    .addComponent(cbfri))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbsat)
                                    .addComponent(cbtue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbwed)
                                    .addComponent(cbsun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbthu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbluname)
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblpswdagain)
                                            .addComponent(ptxtpswdconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblfname)
                                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 21, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbladrs)
                                            .addComponent(txtadrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblage)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbtnmale)
                                            .addComponent(rbtnfemale)
                                            .addComponent(lblgender))
                                        .addGap(3, 3, 3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblsports)
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cbbton)
                                                    .addComponent(cbathletic))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cbvball)
                                                    .addComponent(cbswim))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cbcarom)
                                                    .addComponent(cbchess))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(btnregister))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbnball)
                                                        .addComponent(cbttennis))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblpswd)
                                                    .addComponent(ptxtpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(40, 40, 40)))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnic)
                            .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtxSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltele)
                            .addComponent(txttele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1167, 1167, 1167))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login frmNewForm = new login();
        frmNewForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtteleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleKeyPressed
        // TODO add your handling code here:
         char tele = evt.getKeyChar();
        if(Character.isLetter(tele) || Character.isWhitespace(tele)){
        txttele.setEditable(false);
        }
        else{
        txttele.setEditable(true);
        }
    }//GEN-LAST:event_txtteleKeyPressed

    private void rbtnmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmaleActionPerformed
        // TODO add your handling code here:
          
         Gender=rbtnmale.getText();
    }//GEN-LAST:event_rbtnmaleActionPerformed

    private void rbtnfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfemaleActionPerformed
        // TODO add your handling code here:
        Gender=rbtnfemale.getText();
    }//GEN-LAST:event_rbtnfemaleActionPerformed

    private void cbathleticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbathleticActionPerformed
        // TODO add your handling code here:
       if(cbathletic.isSelected())
         Sports += " Athletic "  +"  ";
         txtxSports.setText(Sports +" " );
       
       
        
    }//GEN-LAST:event_cbathleticActionPerformed

    private void cbvballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbvballActionPerformed
        // TODO add your handling code here:
      if(cbvball.isSelected())
         Sports += " Valleyball "  +"  ";
         txtxSports.setText(Sports +" " );   
         
      
    }//GEN-LAST:event_cbvballActionPerformed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
         char email = evt.getKeyChar();
        if(Character.isWhitespace(email)){
        txtemail.setEditable(false);
        }
        else{
        txtemail.setEditable(true);
        }
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtunameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunameKeyPressed
        // TODO add your handling code here:
          char uname = evt.getKeyChar();
        if(Character.isWhitespace(uname)){
        txtuname.setEditable(false);
        }
        else{
        txtuname.setEditable(true);
        }
    }//GEN-LAST:event_txtunameKeyPressed

    private void ptxtpswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxtpswdKeyPressed
        // TODO add your handling code here:
         char pswd= evt.getKeyChar();
        if(Character.isWhitespace(pswd)){
        ptxtpswd.setEditable(false);
        }
        else{
       ptxtpswd.setEditable(true);
        }
    }//GEN-LAST:event_ptxtpswdKeyPressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        Age = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void cbbtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbtonActionPerformed
        // TODO add your handling code here:
        if(cbbton.isSelected())
         Sports += " Batminton "  +"  ";
         txtxSports.setText(Sports +" " ); 
          
      
                    
    }//GEN-LAST:event_cbbtonActionPerformed

    private void cbswimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbswimActionPerformed
        // TODO add your handling code here:
       if(cbswim.isSelected())
         Sports += " Swimming "  +"  ";
         txtxSports.setText(Sports +" " ); 
          
       
          
    }//GEN-LAST:event_cbswimActionPerformed

    private void cbcaromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcaromActionPerformed
        // TODO add your handling code here:
        if(cbcarom.isSelected())
         Sports += " Carom "  +"  ";
         txtxSports.setText(Sports+" "  );   
        
    }//GEN-LAST:event_cbcaromActionPerformed

    private void cbchessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbchessActionPerformed
        // TODO add your handling code here:
      if(cbchess.isSelected())
         Sports += " Chess"  +"  ";
         txtxSports.setText(Sports +" " );   
        
    }//GEN-LAST:event_cbchessActionPerformed

    private void cbnballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnballActionPerformed
        // TODO add your handling code here:
        if(cbnball.isSelected())
         Sports += " Netball "  +"  ";
         txtxSports.setText(Sports +" " );   
        
    }//GEN-LAST:event_cbnballActionPerformed

    private void cbttennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbttennisActionPerformed
        // TODO add your handling code here:
        if(cbttennis.isSelected())
         Sports += " TableTennis "  +"  ";
         txtxSports.setText(Sports +" " );   
        
    }//GEN-LAST:event_cbttennisActionPerformed

    private void txtxSportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtxSportsMouseClicked
        // TODO add your handling code here:
              JOptionPane.showMessageDialog(this,"Please Select Values");

        
    }//GEN-LAST:event_txtxSportsMouseClicked

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cc_sports_club","root","");

            String NIC = txtnic.getText();
            String FullName = txtfname.getText();
            String Address = txtadrs.getText();
            String Email = txtemail.getText();
            String Telephone = txttele.getText();
            String UserName = txtuname.getText();
            String Password = ptxtpswd.getText();
            String PasswordConfirm = ptxtpswdconfirm.getText();
            String Sports = txtxSports.getText();
            String Dates = txtday.getText();

            if(NIC.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Enter NIC " );
            }
            
            else  if(!((NIC.matches("^([0-9]{9}[vV])$") &&( NIC.length()==10))||NIC.matches("^([0-9]{12})$") &&( NIC.length()==12)))
            {
                JOptionPane.showMessageDialog(this,"Check Again NIC " );

            }

            else if(FullName.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Enter Your Name " );
            }

            else if(Address.isEmpty())
            {

                JOptionPane.showMessageDialog(this,"Please Enter Your Address " );
            }

            else if( Email.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Enter Your Email Address" );
            }
            else if(!(Telephone.matches("^([0-9]{10})$") &&( Telephone.length()==10)))
            {
                JOptionPane.showMessageDialog(this,"Check Again Telephone Number " );

            }
            else if(Telephone.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Enter your Telephone Number " );
            }
            else if( UserName.isEmpty())
            {
                JOptionPane.showMessageDialog(this," Please Enter a UserName ");
            }

            else if( Password.isEmpty())
            {
                JOptionPane.showMessageDialog(this," Please Enter a Password ");
            }
            else if( PasswordConfirm.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Please Confirm Your Password  ");
            }

            else if(!(new String (ptxtpswd.getPassword()).equals(new String(ptxtpswdconfirm.getPassword()))))
            {
                JOptionPane.showMessageDialog(this,"Check Again you confirmed password" );
            }

            else if( Sports.isEmpty())
            {
                JOptionPane.showMessageDialog(this," Please Select Sports you Like. ");
            }
            else if( Dates.isEmpty())
            {
                JOptionPane.showMessageDialog(this," Please Select Dates you Like. ");
            }
            else{
                Statement st = con.createStatement();
                String query1;
                String query2;
                String query3;
                String query4;

                query1 ="INSERT INTO members(NIC,FullName,Address,Age,Gender,Email,Telephone)"  + "VALUES('"+NIC+"','"+FullName+"','"+Address+"','"+Age+"','"+Gender+"','"+Email+"','"+Telephone+"')";
                query2 = "INSERT INTO password (NIC,UserName,Password)" + "VALUES('"+NIC+"','"+UserName +"','"+Password+"')";
                query3 = "INSERT INTO sports(NIC,SportName)" + "VALUE('"+NIC+"','"+ Sports+"')";
                query4= "INSERT INTO dates(NIC,DateName,SportName)" + "VALUE('"+NIC+"','"+Dates+"','"+ Sports+"')";

                st.executeUpdate(query1);
                st.executeUpdate(query2);
                st.executeUpdate(query3);
                st.executeUpdate(query4);

                JOptionPane.showMessageDialog(this,"Registed Successfully");
                Home frmNewForm = new Home();
                frmNewForm .setVisible(true);
                this.dispose();
            }
        }

        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(this,"You have already registered. " + ex1 );

        }

    }//GEN-LAST:event_btnregisterActionPerformed

    private void txtxSportsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxSportsKeyPressed
        // TODO add your handling code here:
        char Sports = evt.getKeyChar();
        if(Character.isLetter(Sports) || Character.isWhitespace(Sports)||  Character.isDigit(Sports)){
            txtxSports .setEditable(false);
        }
        else{
            txtxSports .setEditable(true);

        }

    }//GEN-LAST:event_txtxSportsKeyPressed

    private void txtdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdayMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Please Select Values");
    }//GEN-LAST:event_txtdayMouseClicked

    private void txtdayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdayKeyPressed
        // TODO add your handling code here:
        char dates = evt.getKeyChar();
        if(Character.isLetter(dates ) || Character.isWhitespace(dates )||  Character.isDigit(dates )){
            txtday.setEditable(false);
        }
        else{
            txtday .setEditable(true);

        }
    }//GEN-LAST:event_txtdayKeyPressed

    private void cbmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonActionPerformed
        // TODO add your handling code here:
        if(cbmon.isSelected())
        Dates += " Monday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbmonActionPerformed

    private void cbtueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtueActionPerformed
        // TODO add your handling code here:
        if(cbtue.isSelected())
        Dates += " Tuesday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbtueActionPerformed

    private void cbwedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbwedActionPerformed
        // TODO add your handling code here:
        if(cbwed.isSelected())
        Dates += " Wednesday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbwedActionPerformed

    private void cbthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbthuActionPerformed
        // TODO add your handling code here:
        if(cbthu.isSelected())
        Dates += " Thursday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbthuActionPerformed

    private void cbfriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfriActionPerformed
        // TODO add your handling code here:
        if(cbfri.isSelected())
        Dates += " Friday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbfriActionPerformed

    private void cbsatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsatActionPerformed
        // TODO add your handling code here:
        if(cbsat.isSelected())
        Dates += " Saturday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbsatActionPerformed

    private void cbsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsunActionPerformed
        // TODO add your handling code here:
        if(cbsun.isSelected())
        Dates += " Sunday"  +"  ";
        txtday.setText(Dates +" " );

    }//GEN-LAST:event_cbsunActionPerformed

    private void txtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyPressed
        // TODO add your handling code here:
         char Fname = evt.getKeyChar();
        if(Character.isLetter( Fname ) || Character.isWhitespace( Fname )){
            txtfname  .setEditable(true);
        }
        else{
            txtfname  .setEditable(false);

        }
    }//GEN-LAST:event_txtfnameKeyPressed

      
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registerfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbathletic;
    private javax.swing.JCheckBox cbbton;
    private javax.swing.JCheckBox cbcarom;
    private javax.swing.JCheckBox cbchess;
    private javax.swing.JCheckBox cbfri;
    private javax.swing.JCheckBox cbmon;
    private javax.swing.JCheckBox cbnball;
    private javax.swing.JCheckBox cbsat;
    private javax.swing.JCheckBox cbsun;
    private javax.swing.JCheckBox cbswim;
    private javax.swing.JCheckBox cbthu;
    private javax.swing.JCheckBox cbttennis;
    private javax.swing.JCheckBox cbtue;
    private javax.swing.JCheckBox cbvball;
    private javax.swing.JCheckBox cbwed;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladrs;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lbldays;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblpswd;
    private javax.swing.JLabel lblpswdagain;
    private javax.swing.JLabel lblsports;
    private javax.swing.JLabel lbltele;
    private javax.swing.JLabel lbluname;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JPasswordField ptxtpswd;
    private javax.swing.JPasswordField ptxtpswdconfirm;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private javax.swing.JTextField txtadrs;
    private javax.swing.JTextField txtday;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txttele;
    private javax.swing.JTextField txtuname;
    private javax.swing.JTextField txtxSports;
    // End of variables declaration//GEN-END:variables
}
